# Generated by Django 3.2.13 on 2022-06-16 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='changed',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='peak',
            name='editor',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL, verbose_name='editor'),
        ),
        migrations.AddField(
            model_name='ridge',
            name='changed',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='ridge',
            name='editor',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL, verbose_name='editor'),
        ),
        migrations.AddField(
            model_name='route',
            name='changed',
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='route',
            name='editor',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL, verbose_name='editor'),
        ),
    ]
