# Generated by Django 3.2.13 on 2022-06-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0002_auto_20220616_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='slug',
            field=models.SlugField(max_length=64, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='peak',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='ridge',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='name'),
        ),
    ]
