# Generated by Django 3.2.13 on 2022-08-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0004_auto_20220620_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='recommended_equipment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
