# Generated by Django 4.2 on 2023-05-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0006_peakcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peakcomment',
            options={'ordering': ['created_on'], 'verbose_name': 'peak comment', 'verbose_name_plural': 'peak comments'},
        ),
        migrations.AlterField(
            model_name='peakcomment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='peakcomment',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='peakcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='peakcomment',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='peakcomment',
            name='nickname',
            field=models.CharField(max_length=80, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='peakcomment',
            name='peak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mountains.peak', verbose_name='peak'),
        ),
        migrations.AlterModelTable(
            name='peakcomment',
            table='peak_comment',
        ),
    ]
