# Generated by Django 4.2 on 2023-05-12 11:15

from django.db import migrations, models
import routes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0007_alter_peakcomment_options_alter_peakcomment_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakcomment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=routes.utils.get_image_path, verbose_name='photo'),
        ),
    ]
