# Generated by Django 4.2 on 2023-05-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0009_alter_peakcomment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakcomment',
            name='peak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.peak', verbose_name='peak'),
        ),
    ]
