# Generated by Django 4.2 on 2023-05-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0010_alter_peakcomment_peak'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.peakcomment', verbose_name='parent'),
        ),
    ]
