# Generated by Django 4.2 on 2023-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0012_peakcomment_city_peakcomment_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakcomment',
            name='country_code',
            field=models.CharField(max_length=16, null=True, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='peakcomment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
    ]
