# Generated by Django 4.2 on 2023-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0014_peakcomment_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakcomment',
            name='homepage',
            field=models.URLField(blank=True, null=True, verbose_name='home page'),
        ),
    ]
