# Generated by Django 4.2 on 2023-05-19 05:13

from django.db import migrations, models
import routes.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0015_peakcomment_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakcomment',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=routes.utils.get_image_path, verbose_name='doc'),
        ),
    ]
