# Generated by Django 4.2 on 2023-05-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0016_peakcomment_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='peak',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='peak',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='peakphoto',
            name='description',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ridge',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ridge',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ridgeinfolink',
            name='description',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='route',
            name='descent',
            field=models.TextField(blank=True, null=True, verbose_name='descent'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='route',
            name='difficulty',
            field=models.CharField(
                max_length=3, null=True, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='route',
            name='height_difference',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='height_difference'),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='route',
            name='max_difficulty',
            field=models.CharField(
                max_length=16, null=True, verbose_name='max difficulty'),
        ),
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='route',
            name='ready',
            field=models.BooleanField(default=False, verbose_name='ready'),
        ),
        migrations.AlterField(
            model_name='route',
            name='recommended_equipment',
            field=models.TextField(
                blank=True, null=True, verbose_name='recommended equipment'),
        ),
        migrations.AlterField(
            model_name='route',
            name='short_description',
            field=models.TextField(
                blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_height',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='start_height'),
        ),
        migrations.AlterField(
            model_name='route',
            name='year',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='routephoto',
            name='description',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='description',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='routesection',
            name='angle',
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name='angle'),
        ),
        migrations.AlterField(
            model_name='routesection',
            name='description',
            field=models.TextField(
                blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='routesection',
            name='difficulty',
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='routesection',
            name='length',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='routesection',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='number'),
        ),
    ]
