# Generated by Django 4.2 on 2023-06-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0017_alter_peak_description_alter_peak_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peak',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='ridge',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
